export const GET_CHARACTERS = 'GET_CHARACTERS';
export const PAGINATE_CHARACTERS = 'PAGINATE_CHARACTERS';
export const FILTER_CHARACTER = 'FILTER_CHARACTER';

export const GET_SINGLE_CHARACTER = 'GET_SINGLE_CHARACTER';

export const GET_EPISODES = 'GET_EPISODES';
export const PAGINATE_EPISODES = 'PAGINATE_EPISODES';
export const FILTER_EPISODES = 'FILTER_EPISODES';

export const ADD_TO_MY_WATCH_LIST = 'ADD_TO_MY_WATCH_LIST';
export const GET_MY_WATCH_LIST = 'GET_MY_WATCH_LIST';
export const MARK_EPISODE = 'MARK_EPISODE';
export const DELETE_EPISODE = 'DELETE_EPISODE';

export const GET_LOCATIONS = 'GET_LOCATIONS';
export const PAGINATE_LOCATIONS = 'PAGINATE_LOCATIONS';
export const FILTER_LOCATIONS = 'FILTER_LOCATIONS';
